/*
 * March 22nd 2017
 * U2_A2_Birthday-Soleeman
 * A Birthday Card
 *Rev 1.0 
 */

/**
 *
 * @author sohak9660
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        birthdayCard = new javax.swing.JPanel();
        birthdayCardBackround = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Birthday = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        dateField = new javax.swing.JTextField();
        outputsInformation = new javax.swing.JButton();
        outputedInfo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 102, 255));

        birthdayCard.setBackground(new java.awt.Color(0, 204, 153));
        birthdayCard.setForeground(new java.awt.Color(0, 153, 153));

        birthdayCardBackround.setBackground(new java.awt.Color(204, 102, 255));
        birthdayCardBackround.setFont(new java.awt.Font("Wide Latin", 0, 24)); // NOI18N
        birthdayCardBackround.setForeground(new java.awt.Color(0, 0, 204));
        birthdayCardBackround.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        birthdayCardBackround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_balloons__by_nerdxv.gif"))); // NOI18N
        birthdayCardBackround.setText("Happy Birthday");

        Name.setFont(new java.awt.Font("Vijaya", 0, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(0, 102, 153));
        Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name.setText("Enter Your Name:");

        Birthday.setFont(new java.awt.Font("Vijaya", 0, 18)); // NOI18N
        Birthday.setForeground(new java.awt.Color(0, 102, 153));
        Birthday.setText("Enter you Birthday:");

        nameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameField.setText("Enter Here");

        dateField.setText("Enter Here");

        outputsInformation.setBackground(new java.awt.Color(153, 255, 255));
        outputsInformation.setText("Enter");
        outputsInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputsInformationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout birthdayCardLayout = new javax.swing.GroupLayout(birthdayCard);
        birthdayCard.setLayout(birthdayCardLayout);
        birthdayCardLayout.setHorizontalGroup(
            birthdayCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, birthdayCardLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(birthdayCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(birthdayCardBackround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, birthdayCardLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(outputedInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(44, 44, 44))
            .addGroup(birthdayCardLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(birthdayCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Name)
                    .addComponent(Birthday))
                .addGap(18, 18, 18)
                .addGroup(birthdayCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameField)
                    .addComponent(dateField))
                .addGap(90, 90, 90))
            .addGroup(birthdayCardLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(outputsInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(145, 145, 145))
        );
        birthdayCardLayout.setVerticalGroup(
            birthdayCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(birthdayCardLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(birthdayCardBackround)
                .addGap(76, 76, 76)
                .addGroup(birthdayCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(birthdayCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Birthday)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(outputsInformation)
                .addGap(18, 18, 18)
                .addComponent(outputedInfo)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Help");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(birthdayCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(birthdayCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void outputsInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputsInformationActionPerformed
        
       
        
        //Setting Varbles
        String Birthday = ""; //Var for Birthday
        String Name = "";    //Var for Name
        
        
        //Setting Functions to boxes
        Birthday = dateField.getText(); //Instert Text Here to Get Final message
        Name = nameField.getText();  //Insert Text Here to get Final Message
        
        
        //The Final Output
        outputedInfo.setText(Name + "'s birthday is on "+ Birthday); //Setting Text
        
    }//GEN-LAST:event_outputsInformationActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        //Shuts Down System
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        //Tells User What to do
        outputedInfo.setText("Insert Name and Date in Fields");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Birthday;
    private javax.swing.JLabel Name;
    private javax.swing.JPanel birthdayCard;
    private javax.swing.JLabel birthdayCardBackround;
    private javax.swing.JTextField dateField;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel outputedInfo;
    private javax.swing.JButton outputsInformation;
    // End of variables declaration//GEN-END:variables
}
